site_name: SARXarray Documentation
site_url: https://github.com/motionbylearning/sarxarray/

nav:
  - Getting started: 
    - About SARXarray: index.md
    - Installation: setup.md
    - Usage: usage.md
  - Examples: example.md


theme:
  name: material
  logo: img/sarxarray_logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: pink
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  
plugins:
- mkdocs-jupyter:
      include_source: True
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: no
          merge_init_into_class: yes
          show_submodules: no