# Build Documentation when new release created

name: Build docs
on:
  release:
    types:
      - published

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install .[docs]  
      - name: Deploy docs
        run: mkdocs gh-deploy
